let roomImageUrls = {
  trending: '/assets/room_images/trending.jpg',
  gaming: '/assets/room_images/gaming.jpg',
  animals: '/assets/room_images/animals.jpg',
  business: '/assets/room_images/business.jpg',
  cars: '/assets/room_images/cars.jpg',
  entertainment: '/assets/room_images/entertainment.jpg',
  entrepreneurship: '/assets/room_images/entrepreneurship.png',
  fashion: '/assets/room_images/fashion.jpg',
  food: '/assets/room_images/food.jpg',
  health: '/assets/room_images/health.jpg',
  hodgetwins: '/assets/room_images/hodgetwins.jpg',
  joe_rogan: '/assets/room_images/joe_rogan.jpg',
  music: '/assets/room_images/music.jpg',
  movies: '/assets/room_images/entertainment.jpg',
  politics: '/assets/room_images/politics.png',
  random: '/assets/room_images/random.jpg',
  spirituality: '/assets/room_images/spirituality.jpg',
  sports: '/assets/room_images/sports.jpg',
  technology: '/assets/room_images/technology.jpg',
  travel: '/assets/room_images/travel.jpg',
  wearechange: '/assets/room_images/wearechange.jpg',
}
export default roomImageUrls